ci:
  autoupdate_branch: devel
  autofix_prs: false
  autoupdate_schedule: quarterly
  submodules: true
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.0
    hooks:
    - id: clang-format
      types_or: []
      types: [text]
      files: '\.(cpp|cxx|c|h|hpp|hxx)$'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: https://github.com/BlankSpruce/gersemi
    rev: 0.19.2
    hooks:
      - id: gersemi
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-tabs
